CREATE TABLE SEAT(
    SEAT_ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CATEGORY VARCHAR(25),
    SEAT_NUMBER INTEGER,
    A BOOLEAN,
    B BOOLEAN,
    C BOOLEAN,
    D BOOLEAN
);

CREATE TABLE RESERVATION(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    SEAT_ID INTEGER,
    USER_ID INTEGER,
    A BOOLEAN,
    B BOOLEAN,
    C BOOLEAN,
    D BOOLEAN,
    FOREIGN KEY (SEAT_ID) REFERENCES PLANE(SEAT_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);

CREATE TABLE USER(
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USERNAME VARCHAR(25),
    EMAIL VARCHAR(50),
    SALT VARCHAR(255),
    HASHED_PASSWORD VARCHAR(255)
);